# Generated by Django 4.2.2 on 2023-08-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finecap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="stand",
            field=models.OneToOneField(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="finecap.stand",
            ),
        ),
    ]
