# Generated by Django 4.2.2 on 2023-09-26 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finecap", "0003_alter_reserva_stand"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 26, 12, 54, 44, 667698)
            ),
        ),
    ]
