# Generated by Django 4.2.2 on 2023-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finecap", "0007_alter_reserva_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="data",
            field=models.DateTimeField(),
        ),
    ]
