# Generated by Django 4.2.2 on 2023-08-31 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aluno", "0002_rename_matricula_aluno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="curso",
        ),
    ]
